let item = [
    {name: "Qimir", img: "assets/pictures/cardQimir.png", h3: "Qimir", h4:"Sith Stranger", p: "O ex-Jedi ficou pouco conhecido, mas poucos Jedi sobreviveram. Treinou a Mae e é aprendiz do Mestre Sith Darth Plagueis. Para os poucos que o conheceram notou-se sua extrema habilidade com a Forma Juyo."},
    {name: "Plagueis", img: "assets/pictures/cardPlagueis.png", h3: "Plagueis", h4:"Darth Plagueis", p: "Darth Plagueis foi um Mestre dos Sith. O Muun foi responsável pelo treinamendo de Qimir e Darth Sidious. Também, conhecido por suas incensantes pesquisas usando o Lado Sombrio para alcançar a imortalidade."},
    {name: "Mae", img: "assets/pictures/cardMae.png", h3: "Mae Aniseya", h4:"Acólita " , p: "Criada misteriosamente pela Força com sua irmã idêntica Osha, Mae foi dada como morta após a intervenção do Mestre Sol em seu planeta natal Brendok. Depois que sobreviveu, jurou vingança contra os Jedi, se alinhando com Qimir, o Sith Desconhecido."},
    {name: "Osha", img: "assets/pictures/cardOsha.png", h3: "Osha Aniseya", h4:"Jedi caída" , p: "Criada misteriosamente pela Força com sua irmã idêntica Mae, Osha foi acolhida pelo Mestre Sol após a intervenção em seu planeta natal Brendok. No entanto. Osha falhou como Jedi por nunca aceitar o que havia acontecido no passado. Agora é uma confusa aprendiz de Qimir, após matar seu antigo mestre, Sol."},
    {name: "Sol", img: "assets/pictures/cardSol.png", h3: "Sol", h4:"Mestre Sol" , p: "Excelente guerreiro e um Jedi incompreendi, Mestre Sol induziu uma intervenção em Brendok após descobrir que um misterioso clã de bruxas do Lado Sombrio haviam criado duas pessoas em uma consciência através da Força. Matou a mãe das quase-gêmeas e salvou Osha, na qual levou e treinou-a nas artes Jedi."},
    {name: "Yoda", img: "assets/pictures/cardYoda.png", h3: "Mestre Ypda", h4:"Grande Mestre Yoda" , p: "Vivendo por mais de 800 anos, Yoda, de espécie desconhecida, é um Grande Mestre Jedi e membro do Conselho Jedi, participando de grandes tramas como as Guerras Clônicas. É um Jedi calmo e racional. Também, um implácavel duelista com sabre de luz, usando a Forma Ataru."},
    {name: "Kelnacca", img: "assets/pictures/cardKelnacca.png", h3: "Kelnacca", h4:"Mestre Kelnacca" , p: "O Wookie, conhecido por sua força e sua culinária peculiar, foi um mestre Jedi que participou da intervenção em Brendok, foi possuído pela irmã Koril e atacou seus companheiros. Após os eventos catastróficos da intervenção, Kelnacca se isolou num mundo chamado Khofar. Quando encontrado foi assassino pelo Lord Sith Qimir."},
    {name: "Vernestra ", img: "assets/pictures/cardVernestra.png", h3: "Vernestra Rowh", h4:"Mestra Vernestra" , p: "Mestra Jedi que ficou encarregada de investigar a Mae pelos assinatos de dois mestres Jedi. Treinou Qimir na época que o mesmo ainda era considerado um Jedi."}

];