/* era: 
0 - old republic
1 - prequels
2 - empire
3 - resistance/first order */
let item = [
    /* Era 0 */
    {charImg: "/assets/pictures/charQimir.png",era: 0, align:"evil", name: "Qimir", img: "assets/pictures/cardLuke.png", h3: "Qimir", h4:"Sith Stranger", p: "O ex-Jedi ficou pouco conhecido, mas poucos Jedi sobreviveram. Treinou a Mae e é aprendiz do Mestre Sith Darth Plagueis. Para os poucos que o conheceram notou-se sua extrema habilidade com a Forma Juyo."},
    {charImg: "/assets/pictures/charPlagueis.png", era: 0, align:"evil", name: "Plagueis", img: "assets/pictures/cardPlagueis.png", h3: "Plagueis", h4:"Darth Plagueis", p: "Darth Plagueis foi um Mestre dos Sith. O Muun foi responsável pelo treinamendo de Qimir e Darth Sidious. Também, conhecido por suas incensantes pesquisas usando o Lado Sombrio para alcançar a imortalidade."},
    {charImg: "/assets/pictures/charMae.png", era: 0, align:"evil", name: "Mae", img: "assets/pictures/cardMae.png", h3: "Mae Aniseya", h4:"Acólita " , p: "Criada misteriosamente pela Força com sua irmã idêntica Osha, Mae foi dada como morta após a intervenção do Mestre Sol em seu planeta natal Brendok. Depois que sobreviveu, jurou vingança contra os Jedi, se alinhando com Qimir, o Sith Desconhecido."},
    {charImg: "/assets/pictures/charOsha.png", era: 0, align:"evil", name: "Osha", img: "assets/pictures/cardOsha.png", h3: "Osha Aniseya", h4:"Jedi caída" , p: "Criada misteriosamente pela Força com sua irmã idêntica Mae, Osha foi acolhida pelo Mestre Sol após a intervenção em seu planeta natal Brendok. No entanto. Osha falhou como Jedi por nunca aceitar o que havia acontecido no passado. Agora é uma confusa aprendiz de Qimir, após matar seu antigo mestre, Sol."},
    {charImg: "/assets/pictures/charSol.png", era: 0, align:"good", name: "Sol", img: "assets/pictures/cardSol.png", h3: "Sol", h4:"Mestre Sol" , p: "Excelente guerreiro e um Jedi incompreendo. Mestre Sol induziu uma intervenção em Brendok após descobrir que um misterioso clã de bruxas do Lado Sombrio haviam criado duas pessoas em uma consciência através da Força. Matou a mãe das quase-gêmeas e salvou Osha, na qual levou e treinou-a nas artes Jedi."},
    {charImg: "/assets/pictures/charYoda.png", era: 0, align:"good", name: "Yoda", img: "assets/pictures/cardYoda.png", h3: "Mestre Ypda", h4:"Grande Mestre Yoda" , p: "Vivendo por mais de 800 anos, Yoda, de espécie desconhecida, é um Grande Mestre Jedi e membro do Conselho Jedi, participando de grandes tramas como as Guerras Clônicas. É um Jedi calmo e racional. Também, um implácavel duelista com sabre de luz, usando a Forma Ataru."},
    {charImg: "/assets/pictures/charKelnacca.png", era: 0, align:"good", name: "Kelnacca", img: "assets/pictures/cardKelnacca.png", h3: "Kelnacca", h4:"Mestre Kelnacca" , p: "O Wookie, conhecido por sua força e sua culinária peculiar, foi um mestre Jedi que participou da intervenção em Brendok, foi possuído pela irmã Koril e atacou seus companheiros. Após os eventos catastróficos da intervenção, Kelnacca se isolou num mundo chamado Khofar. Quando encontrado foi assassino pelo Lord Sith Qimir."},
    {charImg: "/assets/pictures/charVernestra.png", era: 0, align:"good", name: "Vernestra ", img: "assets/pictures/cardVernestra.png", h3: "Vernestra Rowh", h4:"Mestra Vernestra" , p: "Mestra Jedi que ficou encarregada de investigar a Mae pelos assinatos de dois mestres Jedi. Treinou Qimir na época que o mesmo ainda era considerado um Jedi."},
    /* Era 1 */
    {charImg: "/assets/pictures/charMaul.png" , era: 1, align: "evil", name: "Maul", img: "assets/pictures/cardMaul.png", h3: "Maul", h4:"Darth Maul" , p:"Maul foi pego quando criança do seu clã em Dathomir por Darth Sidious para ser seu novo Aprendiz com o objetivo de destruir seu antigo mestre Darth Plagueis. O Zabrakk foi cortado ao meio pelo Jedi Obi-Wan Kenobi durante uma luta em Naboo. Maul sobreviveu e jurou vingança ao Jedi. Ademais, está constantemente planejando sua ascenção como novo Mestre dos Sith tramando contra Sidious diversas vezes." },
    {charImg: "/assets/pictures/charSidious.png" , era: 1, align: "evil", name: "Sheev Palpatine", img: "assets/pictures/cardSidious.png", h3: "Darth Sidious", h4: "Imperador Sith", p: "O humano com tendências psicopatas foi encontrado por Darth Plagueis e foi treinado pelo mesmo para ser um Sith. Extremamente inteligente e impiedoso, Darth Sidious foi o Lord Sith mais poderoso já visto: arquitetou as Guerras Clônicas a fim de fazer os Jedi parecerem vilões ante ao senado e ao mesmo tempo usava sua identidade no Senado Galático para manipular os senadores e a galáxia para preparar o cenário para implantar o Império Galático; Criou a Ordem 66 e mestre na Forma Juyo, rivalizando até mesmo com mestre Yoda." },
    {charImg: "/assets/pictures/charDookan.png" , era: 1, align: "evil", name: "Conde Dookan", img: "assets/pictures/cardDookan.png", h3: "Darth Tyrannus", h4: "Lord Sombrio dos Sith", p: "O ex-Jedi Conde Dookan se voltou para o Lado Sombrio sob a influência de Darth Sidious por estar insatisfeito com o modo que os Jedi lidam com as crises e a corrupção no Senado Galático. Um excelente duelista na Forma Makashi e um sábio na Força, Darth Tyrannus foi o braço direito de seu mestre Darth Sidious para espalhar o caos sob a fachada da ideologia da Aliança Separatista." },
    {charImg: "/assets/pictures/charJango.png" , era: 1, align: "evil", name: "Jango Fett", img: "assets/pictures/cardJango.png", h3: "Jango Fett", h4: "Caçador de recompensas", p: "O guerreiro Jango Fett é um caçador de recompensas renomado que foi escolhido por Tyrannus para ser o modelo genético dos clones produzidos do mundo chuvosos Kamino. Em troca, pediu um grande pagamento e uma cópia genética inalterada dele mesmo que seria o filho dele Boba Fett." },
    {charImg: "/assets/pictures/charAnakin.png" , era: 1, align: "good", name: "Anakin Skywalker", img: "assets/pictures/cardAnakin.png", h3: "General Skywalker", h4: "O Escolhido, Cavalheiro Jedi", p: "Anakin possui a maior concentração de midiclorians da galáxia, considerado pelos Jedi 'o Escolhido', acredita-se que o jovem Skywalker é a chave para o equilíbrio da Força de acordo com antiga professia. No entanto, o Mestre Darth Sidious possui outros planos para ele: convertê-lo para o Lado Sombrio e ser o sucessor do mesmo no futuro Império. Anakin é um guerrero implácavel, mestre na Forma Djen-So e mentor de Ahsoka Tano." },
    {charImg: "/assets/pictures/charKenobi.png" , era: 1, align: "good", name: "Obi-Wan Kenobi", img: "assets/pictures/cardKenobi.png", h3: "General Kenobi", h4: "Mestre Jedi Kenobi", p: "Obi-Wan é o mestre de Anakin Skywalker, general do exército da República galática e versado na Forma Suresu. Extremamente disciplinado e ótimo guerreiro, foi posto no Conselho Jedi por sua grande habilidade como Jedi e sua personalidade equilibrada." },
    {charImg: "/assets/pictures/charWindu.png" , era: 1, align: "good", name: "Mace Windu", img: "assets/pictures/cardWindu.png", h3: "General/Mestre Windu", h4: "Grande-Mestre Jedi do Conselho Jedi", p: "Mace Windu é muito poderoso e calmo. O Jedi desenvolveu uma adaptação da Forma Juyo chamada Vaapad, capaz de reter o Lado Sombrio e voltar contra seu oponente. Foi o único Jedi capaz de ganhar de Darth Sidious no duelo." },
    {charImg: "/assets/pictures/charAhsoka.png" , era: 1, align: "good", name: "Ahsoka Tano", img: "assets/pictures/cardAhsoka.png", h3: "General Tano", h4: "Jedi Padawan", p: "Ahsoka é uma jovem Togruta que foi escolhida para ser aprendiz do Cavalheiro Jedi Anakin Skywalker. É uma jovem exemplar, porém, assim como seu mestre, é um pouco impulsiva." }
    /* Era 2 */





];
let era = [
    {id: 0, eraTitle: "Old Repulic (Acolyte)"},
    {id: 1, eraTitle: "Prequels & Clone Wars"},
    {id: 2, eraTitle: "Empire"},
    {id: 3, eraTitle: "Disney's Era"}
];